# Generated by Django 4.0.1 on 2022-02-16 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
