# Generated by Django 4.0.1 on 2022-02-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_project_project_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_time']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_date_time',
            new_name='project_time',
        ),
    ]
