# Generated by Django 4.0.1 on 2022-02-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
